#!/usr/bin/env python3
"""Regenerate the open-items digest at the top of the review tracker.

The tracker is the single record and DONE rows stay where they are: they carry the
commit SHA and the reasoning, and they are most useful sitting next to the open items
on the same theme. But 96 rows averaging 78 words of notes is not scannable, and the
open ones are spread across all 13 sections.

So the fix is an index rather than a reorganisation. This writes a compact digest of
just the not-DONE rows between the DIGEST markers, ordered by severity. It is
generated, so it cannot drift out of sync the way a hand-maintained list would.

    python3 tracker_digest.py            # rewrite the digest
    python3 tracker_digest.py --check    # exit 1 if stale, for a pre-commit check

Nothing outside the markers is touched.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TRACKER = Path("reviews/REVIEW-TRACKER.md")
BEGIN = "<!-- DIGEST:BEGIN (generated by tracker_digest.py; do not edit by hand) -->"
END = "<!-- DIGEST:END -->"

ROW_ID = re.compile(r"^\| ([VRA]-[\w.]+) \|")
SEV_ORDER = {"critical": 0, "significant": 1, "moderate": 2, "minor": 3}
CLOSED = {"DONE", "WONTFIX"}
# The retracted table is deliberately 3 columns (id, item, explanation) and carries no
# status, so it is skipped rather than reported as malformed.
SKIP_SECTIONS = ("retracted",)


def parse(text: str) -> tuple[list[dict], list[str]]:
    """Return (rows, anomalies).

    Cells are split on the pipe rather than matched with one big pattern: 20 rows have
    an empty trailing notes cell, and a monolithic regex silently skipped every one of
    them. A digest that quietly omits open items is worse than no digest, so anything
    unparseable is reported instead of dropped.
    """
    # Never parse the digest's own rows, or regenerating would compound the counts.
    if BEGIN in text and END in text:
        text = text[: text.index(BEGIN)] + text[text.index(END) + len(END) :]

    rows: list[dict] = []
    anomalies: list[str] = []
    section = ""
    for n, line in enumerate(text.split("\n"), 1):
        if line.startswith("## "):
            section = line[3:].strip()
            continue
        if not ROW_ID.match(line):
            continue
        if any(s in section.lower() for s in SKIP_SECTIONS):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            anomalies.append(f"L{n}: {len(cells)} columns, expected 5+: {line[:70]}")
            continue
        rows.append(
            {
                "id": cells[0],
                "item": cells[1],
                "sev": cells[2],
                "status": cells[3],
                "section": section,
                "notes": cells[4] if len(cells) > 4 else "",
            }
        )
    return rows, anomalies


def short_section(s: str) -> str:
    s = re.sub(r"^\d+[-.\d]*\.?\s*", "", s)
    return s.split("(")[0].strip()[:34]


def build_digest(rows: list[dict]) -> str:
    live = [r for r in rows if r["status"] not in CLOSED]
    if not live:
        return f"{BEGIN}\n\nNo open items.\n\n{END}"

    live.sort(key=lambda r: (SEV_ORDER.get(r["sev"].lower(), 9), r["id"]))
    out = [
        BEGIN,
        "",
        "## Open items",
        "",
        "<!-- Editing a status? Edit the row in the numbered sections BELOW, not here. "
        "This table is regenerated, and every row appears twice in this file with "
        "different column orders, so a search for the row id finds this copy first and "
        "any edit to it is silently discarded on the next run. -->",
        "",
        f"Generated index of the {len(live)} rows that are not DONE or WONTFIX, worst first. "
        "Full detail, including why each one matters, stays in the numbered sections below, "
        "where the closed rows on the same theme are still visible for context.",
        "",
        "Regenerate with `python3 tracker_digest.py` after changing any status.",
        "",
        "| ID | Sev | Status | Item | Area |",
        "|----|-----|--------|------|------|",
    ]
    for r in live:
        item = r["item"] if len(r["item"]) <= 78 else r["item"][:75].rstrip() + "..."
        out.append(
            f"| {r['id']} | {r['sev']} | {r['status']} | {item} | {short_section(r['section'])} |"
        )

    by_sev: dict[str, int] = {}
    for r in live:
        by_sev[r["sev"]] = by_sev.get(r["sev"], 0) + 1
    tally = " · ".join(
        f"{k} {v}" for k, v in sorted(by_sev.items(), key=lambda kv: SEV_ORDER.get(kv[0].lower(), 9))
    )
    closed = len(rows) - len(live)
    out += ["", f"**{len(live)} open** ({tally}) · {closed} closed · {len(rows)} total", "", END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the digest is stale")
    args = ap.parse_args()

    text = TRACKER.read_text(encoding="utf-8")
    rows, anomalies = parse(text)
    digest = build_digest(rows)

    if BEGIN in text and END in text:
        i, j = text.index(BEGIN), text.index(END) + len(END)
        new = text[:i] + digest + text[j:]
    else:
        # First run: insert after the H1 and any intro paragraph, before the first "## ".
        k = text.index("\n## ")
        new = text[:k] + "\n" + digest + "\n" + text[k:]

    if args.check:
        if new != text:
            print("  STALE: run python3 tracker_digest.py")
            return 1
        print(f"  digest current ({sum(1 for r in rows if r['status'] not in CLOSED)} open)")
        return 0

    for a in anomalies:
        print(f"  ANOMALY (not indexed) {a}")
    TRACKER.write_text(new, encoding="utf-8")
    live = [r for r in rows if r["status"] not in CLOSED]
    print(f"  digest written: {len(live)} open of {len(rows)} total")
    for sev in sorted({r["sev"] for r in live}, key=lambda s: SEV_ORDER.get(s.lower(), 9)):
        ids = [r["id"] for r in live if r["sev"] == sev]
        print(f"    {sev:12} {len(ids):2d}  {' '.join(ids)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
